#include <string>
 else if (tokens[0] ==  token_pass) {cmd_pass(tokens);}
 else if (tokens[0] ==  token_nick) {cmd_nick(tokens);}
 else if (tokens[0] ==  token_user) {cmd_user(tokens);}
 else if (tokens[0] ==  token_oper) {cmd_oper(tokens);}
 else if (tokens[0] ==  token_quit) {cmd_quit(tokens);}
 else if (tokens[0] ==  token_pong) {cmd_pong(tokens);}
 else if (tokens[0] ==  token_ping) {cmd_ping(tokens);}
 else if (tokens[0] ==  token_join) {cmd_join(tokens);}
 else if (tokens[0] ==  token_part) {cmd_part(tokens);}
 else if (tokens[0] ==  token_mode) {cmd_mode(tokens);}
 else if (tokens[0] ==  token_topic) {cmd_topic(tokens);}
 else if (tokens[0] ==  token_names) {cmd_names(tokens);}
 else if (tokens[0] ==  token_list) {cmd_list(tokens);}
 else if (tokens[0] ==  token_invite) {cmd_invite(tokens);}
 else if (tokens[0] ==  token_kick) {cmd_kick(tokens);}
 else if (tokens[0] ==  token_privmsg) {cmd_privmsg(tokens);}
 else if (tokens[0] ==  token_notice) {cmd_notice(tokens);}
 else if (tokens[0] ==  token_away) {cmd_away(tokens);}
 else if (tokens[0] ==  token_who) {cmd_who(tokens);}
 else if (tokens[0] ==  token_whois) {cmd_whois(tokens);}
 else if (tokens[0] ==  token_whowas) {cmd_whowas(tokens);}
 else if (tokens[0] ==  token_lusers) {cmd_lusers(tokens);}
 else if (tokens[0] ==  token_version) {cmd_version(tokens);}
 else if (tokens[0] ==  token_stats) {cmd_stats(tokens);}
 else if (tokens[0] ==  token_links) {cmd_links(tokens);}
 else if (tokens[0] ==  token_time) {cmd_time(tokens);}
 else if (tokens[0] ==  token_trace) {cmd_trace(tokens);}
 else if (tokens[0] ==  token_admin) {cmd_admin(tokens);}
 else if (tokens[0] ==  token_info) {cmd_info(tokens);}
 else if (tokens[0] ==  token_servlist) {cmd_servlist(tokens);}
 else if (tokens[0] ==  token_squery) {cmd_squery(tokens);}
 else if (tokens[0] ==  token_motd) {cmd_motd(tokens);}
 else if (tokens[0] ==  token_kill) {cmd_kill(tokens);}
 else if (tokens[0] ==  token_error) {cmd_error(tokens);}
 else if (tokens[0] ==  token_rehash) {cmd_rehash(tokens);}
 else if (tokens[0] ==  token_restart) {cmd_restart(tokens);}
 else if (tokens[0] ==  token_squirt) {cmd_squirt(tokens);}
 else if (tokens[0] ==  token_connect) {cmd_connect(tokens);}
 else if (tokens[0] ==  token_die) {cmd_die(tokens);}
